mist-devel/mist-firmware

Makefile, fpga.c, openocd/interface/esa11-ft4232-generic.cfg, user_io.c
After xilinx bitstream is flashed, the SPI lines are left
in some inconsistent state so user_io module can't work
some extra spi reinitialization and retries are performed
and core is now reliably detected after each bitstream upload
on ESA11 board with xc7a102t
=> ESA11 fix the detection of user_io core

usb/hid.c, user_io.c, user_io.h
Not only at the OSD joystick test, but pass extra buttons to the cores, too.
=> Support extra buttons on USB gamepads/joysticks

usb/hid.c
Vid:0079, Pid:0011 are used for very different cheap clone controllers, NES mapping breaks the Sega-style clones. Mist.ini is a better place to define the mapping instead of hardcoding it.
=> unbreak cheap Chinese controllers

user_io.c
...if the core ignores the size.
Maybe would be better to handle at FAT level, but too much bells and whistles there to break.
=> More safety for SD-reads and writes, watch out for file length

usb/joymapping.c
Adds Speedlink SL-650212 Competition Pro Extra USB joystick to the known devices.
=> Add Speedlink SL-650212 Competition Pro Extra USB to known devices

usb/hid.c
Updates the current joystick status in OSD Input Devices -> USB status screen when devices are added/removed.
=> Update current joystick status in OSD USB status screen

usb/hid.c, usb/joymapping.c, usb/joymapping.h
When more than one USB joystick is connected the OSD menu can't be accessed properly because the status of the joysticks are interpreted as consecutive key-press key-release events.
=> Debounce virtual joystick keyboard with more than one USB joystick

config.c
According to the comments in HRTmon's src/HRTmonV2.s valid configuration values for some options are -1 and 0:
```
...
config_RM       dc.b 0                  ;28 -1=right-mouse enter on 0=off
config2         dc.b 0                  ;29 no of keyboard to use
config_key      dc.b 0                  ;30 -1= \ key enter on 0=off
config_IDE      dc.b 0                  ;31 -1= IDE harddisk
config_A1200    dc.b 0                  ;32 -1= A1200
config_AGA      dc.b 0                  ;33 -1= AGA
config_insert   dc.b 0                  ;34 -1= insert
config_delay    dc.b 15                 ;35 repeat key delay (default = 15)
config_lview    dc.b 0                  ;36 -1= lview task
config_elsat    dc.b 0                  ;37 -1=elsat.device IDE (CD32)
config_screen   dc.b 0                  ;38 …
```
=> minimig-mist: use correct config values for hrtmon (-1 instead of 1)

menu.c, osd.c, osd.h
* number of directory name characters to display when scrolling was two chars too wide, ` <DIR>` was partly overwritten.
* added parameter len_offset to ScrollText(). This is required for directory names and file names because they are shifted on OSD display and the len comparison didn't work in some cases:
* directory names were cut at 21 chars but scrolled only if the directory name was larger than 25 chars.
* file names were cut at 28 chars but scrolled only if the file name was larger than 30 chars
=> Fix scrolling of long directory names and file names in OSD

ini_parser.c
Allow tilde in mist.ini.
I have the following files for the C64 core:
```
C64GS    ROM     16384 2020-04-11  19:52  c64gs.rom
C64      RBF    419481 2020-04-30  16:23  c64.rbf
C64GS    ARC        31 2020-04-11  19:52 
C64_JI~1 ROM     32768 2019-02-04  22:31  c64_jiffydos.rom
C64_OR~1 ROM     32768 2020-04-26  10:55  c64_original.rom
```
This change allows to use the short name of a file with long name in mist.ini e.g. for the `rom=` option.
```
[c64]
...
rom=C64_JI~1
```
=> ini_parser: add tilde as special char

data_io.c, hdd_internal.h
Fixes for gcc 9 compiler warnings.
```
hdd.c: In function 'FakeRDB':
hdd.c:124:7: warning: converting a packed 'struct RigidDiskBlock' pointer (alignment 1) to a 'long unsigned int' pointer (alignment 4) may result in an unaligned pointer value [-Waddress-of-packed-member]
124 |       unsigned long *p = (unsigned long*)rdb;
|       ^~~~~~~~
In file included from hdd.c:36:
hdd_internal.h:8:8: note: defined here
8 | struct RigidDiskBlock {
|        ^~~~~~~~~~~~~~
hdd.c:126:7: warning: converting a packed 'struct RigidDiskBlock' pointer (alignment 1) to a 'long unsigned int' pointer (alignment 4) may result in an unaligned pointer value [-Waddress-of-packed-member]
126 |       RDBChecksum((unsigned long *)rdb);
|       ^~~~~~~~~~~
In file included from hdd.c:36:
hdd_internal.h:8:8: note: …
```
=> gcc 9 warnings fixes

fdd.c
There's been a long-standing bug in ADF writes where copying files to an ADF using Workbench would frequently result in a corrupted filesystem.  I've traced it to a single line of code in fdd.c which is intended to prevent bad data when reading back a track that's just been written to - but instead causes bad data when reading the following track!  Setting prev_track to a value that will never match a requested track fixes the issue.
=> Fix long-standing ADF write corruption bug

fat.c
I have a games directory with several subdirectories. To force directories with games collections at the top of the directory list I put a char below '0' as first char in the name (the number sign '#').
The sorted directory is displayed as
```
#collectionA       <DIR>
#collectionB       <DIR>
..                 <DIR>
0                  <DIR>
1                  <DIR>
2                  <DIR>
A                  <DIR>
B                  <DIR>
C                  <DIR>
```
With this commit the directory entry '..' for the parent directory is always put at the top of the list which makes it easier to navigate, e.g. the Home key always gets you to the entry of the parent directory.
=> Always put parent directory entry '..' at top

mist_cfg.c, mist_cfg.h, user_io.c
amiga_mod_keys option for mist.ini to swap left ctrl and capslock and swap alts and windows keys as requested here:
* https://www.atari-forum.com/viewtopic.php?p=407256#p407256
* https://www.atari-forum.com/viewtopic.php?p=410306#p410306
Confirmed working here: https://www.atari-forum.com/viewtopic.php?p=410766#p410766
And requested to include in the firmware here: https://www.atari-forum.com/viewtopic.php?p=415535#p415535
=> Minimig mod keys

minimig-menu.c
This fixes a regression introduced with the restructured menu engine in firmware 211207.
See https://www.atari-forum.com/viewtopic.php?p=427729#p427729
=> minimig-menu.c: fix OSD menu state when loading config

menu.c
See https://www.atari-forum.com/viewtopic.php?p=428228#p428228
=> menu.c: fix button R3 can not be defined

usb/usb.c
Fixes recognition of Speedlink Competition Pro USB joystick
=> usb.c: add 8 bytes device descriptor read before and after set address

hw/AT91SAM/hardware.c, hw/AT91SAM/hardware.h, main.c, usb/hub.c, usb/storage.c, user_io.c
The changes in this PR allow to switch the boot order of SD/USB across resets with the User Button:
* SD, fall back to USB (standard)
* USB, fall back to SD
This is convenient when you want to test something on an USB stick without ejecting the SD card.
Connect USB stick, press and hold User Button, power on MiST -> USB stick is the primary device.
It's always possible to switch between the two priority settings by pressing and holding User Button and then reset MiST.
=> Switch boot from SD/USB with User Button

fat_compat.c, fat_compat.h, main.c, menu.c
Now that we have several variants of boot storage devices (SD/USB, FAT file systems) it may be handy to display some information about it in the OSD system menu, e.g.:
<pre>
SD  /     30436MB / FAT32
</pre>
<pre>
SD  /    121942MB / EXFAT
</pre>
<pre>
USB /       991MB / FAT16
</pre>
<pre>
USB /     14999MB / FAT32
</pre>
=> Show information of booted storage device in OSD system menu

archie.c, firmware.c
Fixes iprintf format string of f_size, e.g.:
**Upgrade file size     : 2**
Upgrade header size   : 512
Upgrade ROM size      : 218148
Upgrade header CRC    : C57F658C
Calculated header CRC : C57F658C
Calculated ROM CRC    : AD52E019
ROM CRC from header   : AD52E019
=> Fix format string of f_size

user_io.c
Successfully tested with AmigaTestKit and JoyPortTest. Middle mouse button is recognized and works.
Also tested: `MButton`, a tool to configure the middle bouse button.
https://aminet.net/package/util/mouse/MButton36_8
e.g. tool type `UP=<lcommand m>`: switch screens with middle mouse button.
=> Enable middle mouse button for minimig core

osd.c, state.c, state.h, usb/hid.c, usb/hidparser.c, usb/hub.c, usb/usb.c, usb/xboxusb.c, usb/xboxusb.h
This PR contains several improvements for USB joysticks. Please let me know if you would prefer to split this PR to more granulated ones.
I tested updated firmware with all USB equipment available to me and didn't found any regressions. 
Below I provide the context for some commits for the history:
**Commit: [hid: fix PSP FuSa gamepad support](https://github.com/mist-devel/mist-firmware/commit/5896ef94af20aae02f16523758fdf46ac8d7350b)**
Firmware v240425 log record with PSP FuSa gamepad connection: [pspfusa_on_v240425.log.txt](https://github.com/user-attachments/files/17083496/pspfusa_on_v240425.log.txt)
Wireshark USB traffic capture: [pspfusa_on_windows.pcapng.zip](https://github.com/user-attachments/files/17083493/pspfusa_on_windows.pcapng.zip)
Issue of PSP FuSa gamepad is that its …
=> Several improvements for USB joysticks support

mist_cfg.c, user_io.c
I have a collection of vintage keyboards which I would like to use with the Minimig core via a suitable USB adapter. What these keyboards all have in common is that they lack Windows keys, without which the core isn't currently usable.
This patch adds two new "amiga_mod_keys" modes, which map Ctrl and Alt to Amiga and Alt (in mode 2) or Ctrl and Alt to Alt and Amiga (i.e. reversed, like the existing mode 1)
In both modes, the Caps Lock key becomes the Ctrl key, but if it's pressed and released with no other key events happening in between, it reverts to being Caps Lock. (In other words, it has "mod-tap".)
=> Added two new Amiga keyboard modes for old keyboard with no GUI keys.

data_io.c, data_io.h, main.c, menu-8bit.c
This change provides the possibility to add custom pluggable processors that can be used to process data before uploading it to the FPGA (uncompress files, process tape files, ...) .It's completely optional and can be enabled in the OSD string by appending a suffix after an 'F' entry like in the following example:
`"F2pACE,ACE,Load ACE;"`
The OSD string is searched for the p entry, and in case it's found registers an special romtype (ROM_PROCESSED) and the required processor id as data_processor_id (ACE in this example).
While uploading the ROM file, in case romtype is ROM_PROCESSED, function data_io_file_tx_processor is used instead, which will try to find the custom processor to handle the file.
New methods data_io_init (to initialize the array of registered plugins) and …
=> data_io ROM processors
